CREATE PROCEDURE [dbo].sp_GetMemberByMemberID
	@PID nvarchar(7)

AS
	SELECT MEMBER.PID, MEMBER.FName, MEMBER.MI, MEMBER.LName, MEMBER.Email, MEMBER.Phone, MEMBER.PhotoPath, MEMBER_ROLE.SemesterID FROM MEMBER
	INNER JOIN MEMBER_ROLE ON MEMBER.PID = MEMBER_ROLE.PID
	WHERE MEMBER.PID = @PID
RETURN 0